input_base: .
output_base: .
clients:
  - name: Officiel
    arguments:
      - [1, 2, 3]
      - [1, 2, 3, 4, 5]
      - [a, A, x, X]
    input:
      path_format: "{0}/{1}/{2}"
      parameters:
        - arg: 0
        - arg: 1
        - arg: 2
    output:
      path_format: "{0}-{1}.{2}"
      parameters:
        - mapping:
            a: b
          key:
            arg: 2
        - arg: 1
        - arg: 0
